USE [master]
GO

/****** Object:  Database [Images]    Script Date: 07/06/2024 11:24:50 ******/
CREATE DATABASE [Images]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Images', FILENAME = N'C:\Users\USER\Images.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Images_log', FILENAME = N'C:\Users\USER\Images_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Images].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Images] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Images] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Images] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Images] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Images] SET ARITHABORT OFF 
GO

ALTER DATABASE [Images] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Images] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Images] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Images] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Images] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Images] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Images] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Images] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Images] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Images] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Images] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Images] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Images] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Images] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Images] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Images] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Images] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Images] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Images] SET  MULTI_USER 
GO

ALTER DATABASE [Images] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Images] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Images] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Images] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Images] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Images] SET QUERY_STORE = OFF
GO

USE [Images]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Images] SET  READ_WRITE 
GO

